name: 🕷️ Spiderman Contribution Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: write

    steps:
      - name: Generate Spiderman Snake Animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: chiragchanchal
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%23FF003C&color_dots=%23161b22,%23002D62,%2300599C,%23FF003C,%23FFFFFF
            dist/github-contribution-grid-snake-dark.svg?color_snake=%23FF003C&color_dots=%23161b22,%23002D62,%2300599C,%23FF003C,%23FFFFFF

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
